import { AppUser, Bid, Conversation, DistressDeal } from "./types";

const now = Date.now();
const DAY = 24 * 3600 * 1000;
const iso = (offsetDays: number) => new Date(now + offsetDays * DAY).toISOString();
const isoH = (offsetHours: number) => new Date(now + offsetHours * 3600 * 1000).toISOString();

export const DEMO_USERS: Record<string, AppUser> = {
  seller_01: {
    id: "seller_01",
    role: "seller",
    name: "Ahmed Al Mansouri",
    avatar_initials: "AM",
    credibility_score: 82,
    deals_completed: 9,
    deals_failed: 0,
    tier: "platinum",
    joined_date: "2023-02-14",
    verification_level: "full",
    phone: "+971501112233",
  },
  investor_01: {
    id: "investor_01",
    role: "investor",
    name: "Sarah Chen",
    avatar_initials: "SC",
    credibility_score: 68,
    deals_completed: 6,
    deals_failed: 1,
    tier: "gold",
    joined_date: "2023-09-02",
    verification_level: "full",
    phone: "+971504445566",
  },
  buyer_01: {
    id: "buyer_01",
    role: "buyer",
    name: "Mohammed Al Farsi",
    avatar_initials: "MF",
    credibility_score: 61,
    deals_completed: 5,
    deals_failed: 1,
    tier: "gold",
    joined_date: "2024-01-20",
    verification_level: "basic",
    phone: "+971507778899",
  },
};

export const DEFAULT_USER_ID = "seller_01";

const deal1Bids: Bid[] = [
  {
    id: "BID-0001",
    deal_id: "DEAL-001",
    bidder_id: "buyer_01",
    bidder_name: "Mohammed Al Farsi",
    bidder_tier: "gold",
    bidder_credibility: 61,
    amount_aed: 2_780_000,
    conditions: "Cash purchase, 14-day close. Subject to survey.",
    validity_days: 14,
    status: "pending",
    ai_legitimacy_score: 88,
    ai_legitimacy_note: "Bid within 1% of asking, cash, fast close — credible and serious.",
    submitted_at: iso(-2),
  },
  {
    id: "BID-0002",
    deal_id: "DEAL-001",
    bidder_id: "INV-023",
    bidder_name: "Sarah Chen (family office)",
    bidder_tier: "platinum",
    bidder_credibility: 91,
    amount_aed: 2_750_000,
    conditions: "Mortgage pre-approved, 21-day close.",
    validity_days: 30,
    status: "pending",
    ai_legitimacy_score: 95,
    ai_legitimacy_note: "Platinum bidder, pre-approved financing, strong track record.",
    submitted_at: iso(-2),
  },
  {
    id: "BID-0003",
    deal_id: "DEAL-001",
    bidder_id: "anon_88",
    bidder_name: "Anonymous Buyer",
    bidder_tier: "bronze",
    bidder_credibility: 14,
    amount_aed: 2_100_000,
    conditions: "No conditions stated.",
    validity_days: 7,
    status: "rejected",
    ai_legitimacy_score: 22,
    ai_legitimacy_note: "25% below asking with no financing detail — flagged as a lowball.",
    submitted_at: iso(-3),
  },
  {
    id: "BID-0004",
    deal_id: "DEAL-001",
    bidder_id: "INV-047",
    bidder_name: "INV-047 (family office)",
    bidder_tier: "gold",
    bidder_credibility: 73,
    amount_aed: 2_810_000,
    conditions: "Cash, immediate close, no survey contingency.",
    validity_days: 14,
    status: "pending",
    ai_legitimacy_score: 91,
    ai_legitimacy_note: "Above asking, cash, no contingencies — highly serious.",
    submitted_at: iso(-1),
  },
  {
    id: "BID-0005",
    deal_id: "DEAL-001",
    bidder_id: "buyer_lowball_2",
    bidder_name: "Withdrawn Bidder",
    bidder_tier: "silver",
    bidder_credibility: 30,
    amount_aed: 2_200_000,
    conditions: "Withdrawn before review.",
    validity_days: 7,
    status: "withdrawn",
    ai_legitimacy_score: 31,
    ai_legitimacy_note: "Below-market and subsequently withdrawn.",
    submitted_at: iso(-4),
  },
];

export const DEMO_DEALS: DistressDeal[] = [
  {
    id: "DEAL-001",
    seller_id: "seller_01",
    title: "Al Reem Island Villa — Urgent Relocation",
    district: "Al Reem Island",
    asset_type: "villa",
    bedrooms: 4,
    size_sqm: 380,
    asking_price_aed: 2_800_000,
    market_value_aed: 3_400_000,
    discount_pct: 17.6,
    distress_reason: "relocation",
    urgency_days: 21,
    description:
      "Owner relocating to London in 3 weeks. Spacious 4-bed waterfront villa on Al Reem Island, recently renovated, vacant on transfer. Priced to move fast.",
    status: "bidding",
    distress_score: 74,
    deal_quality_score: 81,
    ai_summary:
      "Owner relocating to London in 3 weeks. Priced 17.6% below comparable Al Reem sales Q1 2026. Strong rental yield district at 6.2% gross. Tight timeline creates genuine buyer leverage.",
    ai_green_flags: [
      "Motivated seller with hard deadline",
      "17.6% discount vs district average",
      "Strong rental yield district gross 6.2%",
    ],
    ai_red_flags: ["Short inspection window", "Title transfer timeline may be tight"],
    matched_investors: [
      {
        investor_id: "INV-023",
        investor_type: "family_office",
        capital_range_aed: "50M-200M",
        match_score: 94,
        match_reasons: [
          "Residential mandate aligned with villa asset",
          "Al Reem Island in preferred-district set",
          "Balanced risk tolerates short-timeline distress",
        ],
        risk_alignment: "Balanced profile fits a 17.6% discount with clean title.",
        recommended_action: "Contact immediately",
      },
      {
        investor_id: "INV-047",
        investor_type: "family_office",
        capital_range_aed: "30M-120M",
        match_score: 88,
        match_reasons: ["Capital range fits AED 2.8M ticket", "Strong residential track record"],
        risk_alignment: "Comfortable with relocation-driven distress.",
        recommended_action: "Schedule call",
      },
      {
        investor_id: "INV-112",
        investor_type: "hnwi",
        capital_range_aed: "8M-40M",
        match_score: 81,
        match_reasons: ["Yield-focused buyer", "Island waterfront preference"],
        risk_alignment: "Seeks 6%+ gross yield — district delivers 6.2%.",
        recommended_action: "Add to watchlist",
      },
    ],
    bids: deal1Bids,
    bid_slots: 5,
    bid_deadline: iso(21),
    chain_hash: "0x3f9a8c12...c721",
    chain_status: "on_chain",
    created_at: iso(-5),
    views: 184,
    latitude: 24.493,
    longitude: 54.406,
    completion_status: "off_plan",
    developer: "Aldar",
    handover_date: "2026-12-01",
    payment_plan: "60/40 on handover",
    paid_pct: 55,
  },
  {
    id: "DEAL-002",
    seller_id: "seller_02",
    title: "Downtown Abu Dhabi Office Stack — Debt Liquidation",
    district: "Al Maryah Island",
    asset_type: "commercial",
    bedrooms: null,
    size_sqm: 620,
    asking_price_aed: 4_100_000,
    market_value_aed: 5_200_000,
    discount_pct: 21.2,
    distress_reason: "debt",
    urgency_days: 45,
    description:
      "Commercial office stack on Al Maryah Island under debt-restructuring pressure. Existing tenant in place paying AED 310k/year. Rare income-producing distress asset in the financial district.",
    status: "matched",
    distress_score: 82,
    deal_quality_score: 76,
    ai_summary:
      "Commercial stack under debt pressure. 21% below market. Existing tenant pays 310k per year. Rare income-producing distress deal in prime downtown location.",
    ai_green_flags: [
      "21.2% discount vs market value",
      "In-place tenant — immediate AED 310k/yr income",
      "Prime financial-district location",
    ],
    ai_red_flags: ["Debt encumbrance to clear at close", "Single-tenant concentration risk"],
    matched_investors: [
      {
        investor_id: "INV-008",
        investor_type: "institutional",
        capital_range_aed: "200M-800M",
        match_score: 90,
        match_reasons: ["Commercial mandate", "Income-producing asset fits hold strategy"],
        risk_alignment: "Institutional appetite for tenanted commercial distress.",
        recommended_action: "Contact immediately",
      },
      {
        investor_id: "INV-031",
        investor_type: "reit",
        capital_range_aed: "400M-1.5B",
        match_score: 85,
        match_reasons: ["REIT seeks yield-bearing offices", "Maryah Island core market"],
        risk_alignment: "Stable income aligns with REIT distribution needs.",
        recommended_action: "Schedule call",
      },
      {
        investor_id: "INV-066",
        investor_type: "private_equity",
        capital_range_aed: "150M-600M",
        match_score: 79,
        match_reasons: ["Opportunistic on debt-driven discounts"],
        risk_alignment: "Aggressive PE comfortable clearing encumbrances.",
        recommended_action: "Add to watchlist",
      },
    ],
    bids: [],
    bid_slots: 3,
    bid_deadline: iso(45),
    chain_hash: "0x7b21de44...90af",
    chain_status: "verified",
    created_at: iso(-3),
    views: 97,
    latitude: 24.5,
    longitude: 54.39,
    completion_status: "ready",
    developer: "Mubadala",
    handover_date: null,
    payment_plan: "Cash / income-producing",
    paid_pct: 100,
  },
  {
    id: "DEAL-003",
    seller_id: "seller_03",
    title: "Yas Island Townhouse — Probate Sale",
    district: "Yas Island",
    asset_type: "townhouse",
    bedrooms: 3,
    size_sqm: 240,
    asking_price_aed: 1_650_000,
    market_value_aed: 1_900_000,
    discount_pct: 13.2,
    distress_reason: "probate",
    urgency_days: 60,
    description:
      "Estate sale of a 3-bed townhouse on Yas Island. Executors seeking an orderly sale within the quarter. Well-maintained, family-friendly community near leisure attractions.",
    status: "bidding",
    distress_score: 58,
    deal_quality_score: 72,
    ai_summary:
      "Probate-driven sale priced 13.2% below Yas Island comparables. Moderate urgency gives buyers room to diligence. Leisure-district demand supports resale liquidity.",
    ai_green_flags: [
      "13.2% discount vs district average",
      "Executors motivated for orderly close",
      "High-demand leisure district",
    ],
    ai_red_flags: ["Probate paperwork can extend timeline", "Smaller discount than peer distress deals"],
    matched_investors: [
      {
        investor_id: "INV-019",
        investor_type: "hnwi",
        capital_range_aed: "15M-60M",
        match_score: 83,
        match_reasons: ["Residential focus", "Yas Island lifestyle preference"],
        risk_alignment: "Conservative buyer suited to clean probate asset.",
        recommended_action: "Schedule call",
      },
      {
        investor_id: "INV-054",
        investor_type: "family_office",
        capital_range_aed: "30M-120M",
        match_score: 77,
        match_reasons: ["Buy-and-hold townhouse strategy"],
        risk_alignment: "Balanced, patient capital fits 60-day window.",
        recommended_action: "Add to watchlist",
      },
    ],
    bids: [],
    bid_slots: 4,
    bid_deadline: iso(60),
    chain_hash: "0x2c90ff31...11be",
    chain_status: "verified",
    created_at: iso(-2),
    views: 53,
    latitude: 24.49,
    longitude: 54.603,
    completion_status: "off_plan",
    developer: "Aldar",
    handover_date: "2027-03-01",
    payment_plan: "50/50 post-handover",
    paid_pct: 40,
  },
  {
    id: "DEAL-004",
    seller_id: "seller_04",
    title: "Mussafah Industrial Unit — Foreclosure",
    district: "Mussafah",
    asset_type: "warehouse",
    bedrooms: null,
    size_sqm: 900,
    asking_price_aed: 2_200_000,
    market_value_aed: 3_100_000,
    discount_pct: 29,
    distress_reason: "foreclosure",
    urgency_days: 14,
    description:
      "Bank-led foreclosure of a 900 sqm industrial unit in Mussafah. Must clear within two weeks. Deep discount reflects forced-sale timeline.",
    status: "ai_scoring",
    distress_score: 91,
    deal_quality_score: 68,
    ai_summary: "AI scoring in progress — analyzing against Mussafah industrial comparables…",
    ai_green_flags: [],
    ai_red_flags: [],
    matched_investors: [],
    bids: [],
    bid_slots: 6,
    bid_deadline: iso(14),
    chain_hash: "0x9ad4be77...4f02",
    chain_status: "unverified",
    created_at: iso(-1),
    views: 31,
    latitude: 24.35,
    longitude: 54.5,
    completion_status: "ready",
    developer: "Private",
    handover_date: null,
    payment_plan: "Cash on foreclosure",
    paid_pct: 100,
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: "CONV-001",
    deal_id: "DEAL-001",
    deal_title: "Al Reem Island Villa — Urgent Relocation",
    participant_id: "buyer_01",
    participant_name: "Mohammed Al Farsi",
    participant_role: "buyer",
    participant_phone: "+971507778899",
    seller_id: "seller_01",
    seller_name: "Ahmed Al Mansouri",
    messages: [
      {
        id: "M-001",
        sender_id: "buyer_01",
        sender_name: "Mohammed Al Farsi",
        sender_role: "buyer",
        text: "Salam Ahmed, very interested in the Al Reem off-plan villa. Is the 60/40 payment plan transferable to me on assignment?",
        timestamp: isoH(-50),
      },
      {
        id: "M-002",
        sender_id: "seller_01",
        sender_name: "Ahmed Al Mansouri",
        sender_role: "seller",
        text: "Wa alaikum salam. Yes, Aldar approves assignment once 30% is paid — we are at 55%, so it's clean to transfer.",
        timestamp: isoH(-49),
      },
      {
        id: "M-003",
        sender_id: "buyer_01",
        sender_name: "Mohammed Al Farsi",
        sender_role: "buyer",
        text: "Perfect. I can do a cash settlement of your paid equity and take over the remaining installments. Can we view this week?",
        timestamp: isoH(-48),
      },
      {
        id: "M-004",
        sender_id: "seller_01",
        sender_name: "Ahmed Al Mansouri",
        sender_role: "seller",
        text: "Yes, Thursday 5pm works. I'll share the SPA and payment receipts before then.",
        timestamp: isoH(-47),
      },
      {
        id: "M-005",
        sender_id: "buyer_01",
        sender_name: "Mohammed Al Farsi",
        sender_role: "buyer",
        text: "Great, confirmed. I'll place a formal bid at AED 2.78M today. Ready to move fast given your timeline.",
        timestamp: isoH(-24),
      },
    ],
  },
  {
    id: "CONV-002",
    deal_id: "DEAL-001",
    deal_title: "Al Reem Island Villa — Urgent Relocation",
    participant_id: "investor_01",
    participant_name: "Sarah Chen",
    participant_role: "investor",
    participant_phone: "+971504445566",
    seller_id: "seller_01",
    seller_name: "Ahmed Al Mansouri",
    messages: [
      {
        id: "M-101",
        sender_id: "investor_01",
        sender_name: "Sarah Chen",
        sender_role: "investor",
        text: "Hi Ahmed — family office here. We like the yield profile. Financing is pre-approved, so we can close in 21 days.",
        timestamp: isoH(-40),
      },
      {
        id: "M-102",
        sender_id: "seller_01",
        sender_name: "Ahmed Al Mansouri",
        sender_role: "seller",
        text: "Appreciated. The relocation deadline is firm — 3 weeks. A 21-day close is workable if docs move quickly.",
        timestamp: isoH(-39),
      },
      {
        id: "M-103",
        sender_id: "investor_01",
        sender_name: "Sarah Chen",
        sender_role: "investor",
        text: "Understood. We'd bid 2.75M, slightly under asking, but with zero contingencies. Reliability over headline price.",
        timestamp: isoH(-20),
      },
    ],
  },
  {
    id: "CONV-003",
    deal_id: "DEAL-003",
    deal_title: "Yas Island Townhouse — Probate Sale",
    participant_id: "investor_01",
    participant_name: "Sarah Chen",
    participant_role: "investor",
    participant_phone: "+971504445566",
    seller_id: "seller_03",
    seller_name: "Estate Executor",
    messages: [
      {
        id: "M-201",
        sender_id: "investor_01",
        sender_name: "Sarah Chen",
        sender_role: "investor",
        text: "Hello, is the post-handover plan still active on this Yas townhouse? The price feels a bit high for a 13% discount.",
        timestamp: isoH(-30),
      },
      {
        id: "M-202",
        sender_id: "seller_03",
        sender_name: "Estate Executor",
        sender_role: "seller",
        text: "It is active. Probate paperwork is with the court; we expect clearance in ~6 weeks.",
        timestamp: isoH(-26),
      },
      {
        id: "M-203",
        sender_id: "investor_01",
        sender_name: "Sarah Chen",
        sender_role: "investor",
        text: "Six weeks is longer than we'd like. I'll reconsider and revert — might be too slow for our cycle.",
        timestamp: isoH(-10),
      },
    ],
  },
];
